apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-app-configuration
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: llamacpp
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $k, $v := index .Values "app-configuration" }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
