apiVersion: v2
name: kube-net-master
description: Kubernetes manifests export to nginx and dnsmasq
type: application
annotations:
  licenses: MIT License
home: https://github.com/mixa3607/charts/tree/master/charts/kube-net-master
icon: https://raw.githubusercontent.com/mixa3607/charts/refs/heads/master/charts/kube-net-master/icon.png
keywords: []
maintainers:
  - name: mixa3607
    url: https://github.com/mixa3607
sources:
  - https://github.com/mixa3607/kube-net-master
version: 0.1.0
appVersion: 0.1.0
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
